# Generated by Django 3.1.7 on 2021-04-10 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imdb_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('plot', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('poster_url', models.CharField(blank=True, max_length=255, null=True)),
                ('backdrop_url', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_cast', models.CharField(blank=True, max_length=5000, null=True)),
                ('raw_genres', models.CharField(blank=True, max_length=2000, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
