# Generated by Django 3.1.7 on 2021-04-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_api', '0002_auto_20210419_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='raw_genres',
        ),
    ]
