# Generated by Django 3.1.7 on 2021-04-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_api', '0006_auto_20210420_2208'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviecrewmember',
            unique_together={('crew_member', 'movie')},
        ),
    ]
