# Generated by Django 3.1.7 on 2021-04-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierecommendation',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movierecommendationcomment',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
